## Simulation

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
def sample_cards(N, n, k):
    """
    Generates a simulated sample of how the cards are shuffled among players. 
    
    Arguments: 
        - N : Total number of cards
        - n : Number of players
        - k : Number of cards per player
        
    Returns: 
        - 2D numpy array where each row represent each player and each column their card in ascending order. 
    """
    
    assert n * k <= N, "There are not enough cards for all the players!"
    
    _cards = np.random.choice(a=np.arange(1, N+1), size=n*k, replace=False)
    _cards = _cards.reshape(n,k)
    _cards.sort(axis=1)
    return _cards

In [25]:
cards = sample_cards(100, 6, 3)
cards

array([[ 53,  63,  82],
       [ 16,  67,  95],
       [  1,  35,  71],
       [ 40,  57,  75],
       [ 24,  44, 100],
       [ 56,  93,  97]])

In [26]:
player0 = cards[0,:]
player1 = cards[1,:]
player0, player1

(array([53, 63, 82]), array([16, 67, 95]))

The lowest card in the game is

In [27]:
np.min(cards)

1

In [23]:
np.arange(1, 5)

array([1, 2, 3, 4])

### What is the distribution of the lowest number in the sample? 

Repeat the sampling of the cards multiple times for the same choice of `N`, `n` and `k` and plot the distribution of the lowest number in the sample. Use an [histogram](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.hist.html) to plot the distribution and set the bins to be the available integer number cards. 

In [ ]:
# To Do cell

### Compare the obtained distribution with other distributions in the literature. 

### What happens when $n * k << N$?